services:
  postgres:
    image: postgres:latest
    container_name: auth-starter
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: database
    volumes:
      - ./data/database/pg_data:/var/lib/postgresql/data

volumes:
  pg_data: